const arr = [
  {
    modelName: "Sleep",
    targetColumn: "duration",
    number: "7:30",
    goalMetric: "sleepDuration",
    operator: ">=",
    format: "hours",
    frequency: "day",
    today: false,
    href: "/sleep",
    dbQuery: { goalResult: "07:43" },
    passing: false,
  },
  {
    modelName: "Exercise",
    targetColumn: "exercise",
    number: "15:00",
    goalMetric: "avg",
    operator: ">=",
    format: "minutes",
    frequency: "day",
    today: false,
    href: "/exercise",
    dbQuery: { goalResult: "11:10" },
    passing: false,
  },
  {
    modelName: "Exercise",
    targetColumn: "stretching",
    number: "90%",
    goalMetric: "avg",
    operator: ">=",
    format: "percentage",
    frequency: "day",
    today: false,
    href: "/exercise",
    dbQuery: { goalResult: "95.27%" },
    passing: false,
  },
  {
    modelName: "Drink",
    targetColumn: "n_drinks",
    number: "0.3",
    goalMetric: "avg",
    operator: "<=",
    format: "units",
    frequency: "day",
    today: false,
    href: "/drink",
    dbQuery: { goalResult: "0.47" },
    passing: false,
  },
  {
    modelName: "Sensimilla",
    targetColumn: "mg",
    number: "15.0",
    goalMetric: "avg",
    operator: "<=",
    format: "units",
    frequency: "day",
    today: false,
    href: "/sensimilla",
    dbQuery: { goalResult: "22.25" },
    passing: false,
  },
  {
    modelName: "Sensimilla",
    targetColumn: "j",
    number: "0.05",
    goalMetric: "avg",
    operator: "<=",
    format: "units",
    frequency: "day",
    today: false,
    href: "/sensimilla",
    dbQuery: { goalResult: "0.15" },
    passing: false,
  },
  {
    modelName: "Vitamin",
    targetColumn: "hair_oil",
    number: "50%",
    goalMetric: "avg",
    operator: ">=",
    format: "percentage",
    frequency: "day",
    today: false,
    href: "/vitamin",
    dbQuery: { goalResult: "57.75%" },
    passing: false,
  },
];
